tag-names:
  - name: datetime
    type: datetime
    value: '%Y%m%d%H%M'

builds:
  test:
    context: /
    dockerfile: Dockerfile.test
    dockerignore:
      - .git

  docker-make:
    context: /
    dockerfile: Dockerfile
    pushes:
      - 'always=vladkolodka/docker-make:{fcommitid}'
      - 'always=vladkolodka/docker-make:{datetime}'
      - 'on_tag=vladkolodka/docker-make:{git_tag}'
      - 'on_branch:master=vladkolodka/docker-make:latest'
    labels:
      - 'com.dockermake.git.describe={git_describe}'
    dockerignore:
      - .git
